"""Modern web misconfiguration checks — the stuff AI-built sites ship with.

All low-risk: passive header reads, single GET probes, benign content.
Nothing here writes state or runs code on the target.

Import hub: implementations live in core/checks/*.py; this module
re-exports every name so existing imports keep working.
"""
from __future__ import annotations

from core.checks._shared import EVIL_HOST, EVIL_ORIGIN, _mask, _same_host
from core.checks.headers import (REQUIRED_HEADERS, test_security_headers, _header_ci, _audit_csp, _audit_hsts, test_cors, test_http_methods, CACHE_HINT_HEADERS, RESET_HINT, _reset_poison_probe, test_host_header, test_cache_poisoning, test_cache_deception, test_security_txt, _session_cookie_exposed, TOKEN_NAME_RE, SESSION_COOKIE_RE, test_csrf_surface)
from core.checks.movement import (REDIRECT_KEYS, TRAVERSAL_KEYS, TRAVERSAL_SETS, TRAVERSAL_CONFIRM, TRAVERSAL_CONFIRM_APP, _get_no_redirect, test_open_redirect, test_oauth_redirect, _filter_proof, test_path_traversal, test_crlf_injection)
from core.checks.secrets import (SECRET_RES, PLACEHOLDER_HINT, JWT_RE, _jwt_alg, test_jwt_none, test_jwt_acceptance, test_js_secrets, FIREBASE_RE, FIREBASE_PROJ_RE, test_firebase_open, SUPABASE_URL_RE, SUPABASE_KEY_RE, PRIVATE_TABLES, test_supabase_anon, S3_URL_RE, GCS_URL_RE, AZURE_BLOB_RE, LIST_MARKERS, _cloud_candidates, test_cloud_storage, test_deserialize_surface, test_ci_workflow)
from core.checks.apps import (GRAPHQL_PATHS, test_graphql_introspection, _dump, OS_CMD_PAYLOADS, OS_CMD_RES, test_os_command_injection, NEXTJS_HINTS, test_nextjs_middleware_bypass, test_wp_user_enum, SWAGGER_HINTS, test_swagger_exposed, ROLE_RE, test_mass_assignment, TLS_EXPIRY_WARN_DAYS, WEAK_CIPHER_HINTS, _cert_names, _hostname_matches, _cert_times, _is_self_signed, _cipher_is_weak, _tls_handshake, _tls_chain_handshake, test_tls_audit, VERSION_FILE_CANDS, DRUPAL_VER_RE, _version_file_version, test_vuln_components, test_atlassian_fileread, test_plugin_install_authz, collect_ws_urls, test_websocket_fuzz)

__all__ = [
    "EVIL_HOST",
    "EVIL_ORIGIN",
    "_mask",
    "_same_host",
    "REQUIRED_HEADERS",
    "test_security_headers",
    "_header_ci",
    "_audit_csp",
    "_audit_hsts",
    "test_cors",
    "test_http_methods",
    "CACHE_HINT_HEADERS",
    "RESET_HINT",
    "_reset_poison_probe",
    "test_host_header",
    "test_cache_poisoning",
    "test_cache_deception",
    "test_security_txt",
    "_session_cookie_exposed",
    "TOKEN_NAME_RE",
    "SESSION_COOKIE_RE",
    "test_csrf_surface",
    "REDIRECT_KEYS",
    "TRAVERSAL_KEYS",
    "TRAVERSAL_SETS",
    "TRAVERSAL_CONFIRM",
    "TRAVERSAL_CONFIRM_APP",
    "_get_no_redirect",
    "test_open_redirect",
    "test_oauth_redirect",
    "_filter_proof",
    "test_path_traversal",
    "test_crlf_injection",
    "SECRET_RES",
    "PLACEHOLDER_HINT",
    "JWT_RE",
    "_jwt_alg",
    "test_jwt_none",
    "test_jwt_acceptance",
    "test_js_secrets",
    "FIREBASE_RE",
    "FIREBASE_PROJ_RE",
    "test_firebase_open",
    "SUPABASE_URL_RE",
    "SUPABASE_KEY_RE",
    "PRIVATE_TABLES",
    "test_supabase_anon",
    "S3_URL_RE",
    "GCS_URL_RE",
    "AZURE_BLOB_RE",
    "LIST_MARKERS",
    "_cloud_candidates",
    "test_cloud_storage",
    "test_deserialize_surface",
    "test_ci_workflow",
    "GRAPHQL_PATHS",
    "test_graphql_introspection",
    "_dump",
    "OS_CMD_PAYLOADS",
    "OS_CMD_RES",
    "test_os_command_injection",
    "NEXTJS_HINTS",
    "test_nextjs_middleware_bypass",
    "test_wp_user_enum",
    "SWAGGER_HINTS",
    "test_swagger_exposed",
    "ROLE_RE",
    "test_mass_assignment",
    "TLS_EXPIRY_WARN_DAYS",
    "WEAK_CIPHER_HINTS",
    "_cert_names",
    "_hostname_matches",
    "_cert_times",
    "_is_self_signed",
    "_cipher_is_weak",
    "_tls_handshake",
    "_tls_chain_handshake",
    "test_tls_audit",
    "VERSION_FILE_CANDS",
    "DRUPAL_VER_RE",
    "_version_file_version",
    "test_vuln_components",
    "test_atlassian_fileread",
    "test_plugin_install_authz",
    "collect_ws_urls",
    "test_websocket_fuzz",
]
